spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:weatherdb
  h2:
    console:
      enabled: true

weather-stack:
  api-url: http://api.weatherstack.com/current?access_key=58b851e0323ec57644cce7284fac79da&query=